# Generated by Django 3.0.11 on 2020-12-15 21:22

import chipstore.utils.common
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('uri', models.URLField(max_length=400)),
                ('foto', models.ImageField(upload_to=chipstore.utils.common.get_image_directory_path)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemWhishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Item')),
            ],
            options={
                'verbose_name': 'ItemWhishList',
                'verbose_name_plural': 'ItemWhishLists',
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('api_key', models.CharField(max_length=80)),
                ('base_api_url', models.URLField()),
                ('base_web_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
            },
        ),
        migrations.CreateModel(
            name='WhishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('item', models.ManyToManyField(through='tienda.ItemWhishList', to='tienda.Item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhishList',
                'verbose_name_plural': 'WhishLists',
            },
        ),
        migrations.AddField(
            model_name='itemwhishlist',
            name='whishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.WhishList'),
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Compra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Item')),
            ],
            options={
                'verbose_name': 'ItemCompra',
                'verbose_name_plural': 'ItemCompras',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='item',
            field=models.ManyToManyField(through='tienda.ItemCompra', to='tienda.Item'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
