# Generated by Django 3.0.11 on 2020-12-19 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.Tienda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(choices=[('BESTBUY', 'Best Buy'), ('TARGET', 'Target')], max_length=80, unique=True, verbose_name='Tienda disponible de dispositivo'),
        ),
    ]
