# Generated by Django 3.0.11 on 2020-12-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20201219_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
