# Generated by Django 3.0.11 on 2020-12-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20201219_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
