# Generated by Django 3.0.11 on 2020-12-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_compra_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemwhishlist',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
